{{- if .Values.web.enabled -}}
{{- if .Values.web.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "concourse.web.fullname" . -}}
{{- $servicePort := .Values.concourse.web.bindPort -}}
{{- $apiVersion := include "concourse.ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "concourse.web.fullname" . }}
  labels:
    app: {{ template "concourse.web.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- range $key, $value := .Values.web.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.web.ingress.hosts }}
    - host: {{ if .name }}{{ .name }}{{ else }}{{ . }}{{ end }}
      http:
        paths:
          {{- if .additionalEarlierPaths }}
          {{- toYaml .additionalEarlierPaths | nindent 10 }}
          {{- end }}
          {{- if or (eq $apiVersion "extensions/v1beta1") (eq $apiVersion "networking.k8s.io/v1beta1") }}
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- else }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  {{- if typeIs "string" $servicePort }}
                  name: {{ $servicePort }}
                  {{- else }}
                  number: {{ $servicePort }}
                  {{- end }}
          {{- end }}
    {{- end -}}
  {{- if .Values.web.ingress.tls }}
  tls:
{{ toYaml .Values.web.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
