apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  post-start-hook.sh: |
    #!/bin/bash
    losetup -d $(losetup -a | grep "volumes\.img (deleted)" | cut -d: -f1)
    exit 0
  pre-stop-hook.sh: |
    #!/bin/bash
    pid=$(pgrep -o -f "entrypoint.sh worker")
    while true; do
      kill -s {{ .Values.concourse.worker.shutdownSignal }} $pid
      for i in {0..60}; do
        sleep 1
        if ! [ -e /proc/$pid ]; then
          exit 0
        fi
      done
    done
