apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "concourse.worker.fullname" . }}
  labels:
    app: {{ template "concourse.worker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  post-start-hook.sh: |
    #!/bin/bash
    losetup -d $(losetup -a | grep "volumes\.img (deleted)" | cut -d: -f1)
    exit 0
  pre-stop-hook.sh: |
    #!/bin/bash
    pid=$(pgrep -o -f "entrypoint.sh worker")
    while true; do
      kill -s {{ .Values.concourse.worker.shutdownSignal }} $pid
      for i in {0..60}; do
        sleep 1
        if ! [ -e /proc/$pid ]; then
          exit 0
        fi
      done
    done
  teardown-entrypoint.sh: |
    #!/usr/bin/sh
    apk add --no-cache losetup
    while true; do
      pid=$(pgrep -o -f "entrypoint.sh worker")
      # Get loop devices from the main container and store them
      nsenter --mount=/proc/${pid}/ns/mnt mount | grep loop | cut -d\  -f1 > /tmp/loopdev.txt
      sleep 60
    done
  teardown-pre-stop-hook.sh: |
    #!/usr/bin/sh
    while true; do
      if ! pgrep concourse >/dev/null 2>&1; then

        # Wait until filesystem is no longer busy
        while (lsof | grep "${CONCOURSE_WORK_DIR}/volumes") >/dev/null 2>&1; do
          sleep 1
        done

        # Detach main container loop devices
        cat /tmp/loopdev.txt | xargs -r -n1 losetup -d

        exit 0
      fi

      sleep 1
    done
